# Generated by Django 3.1.3 on 2020-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='lft',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='rght',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='tree_id',
            field=models.IntegerField(default=1),
        ),
    ]
