# Generated by Django 3.1.3 on 2020-12-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20201202_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorstory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
