# Generated by Django 3.1.3 on 2020-12-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='tag_id',
            field=models.ManyToManyField(blank=True, to='question.Tag'),
        ),
    ]
